var mainData = [
  {
    title: "Unit 1 - Chicken Rice",
    subtitle: "Unit 1",
    testdate: "Test Date 26/01/2023",
    words: [
      "dish",
      "lunch",
      "stall",
      "buzz",
      "hope",
      "snake",
      "crispy",
      "spicy",
      "delicious",
      "tasteless",
      "fresh",
      "disgusting",
      "ingredients",
      "curry puff",
      "chicken rice"
    ],
    meanings: [],
    meanings_cn: [
      "菜肴；盘子",
      "午餐",
      "摊位",
      "嗡嗡声",
      "希望",
      "蛇",
      "脆的",
      "辣的",
      "美味的",
      "无味的",
      "新鲜的",
      "令人厌恶的",
      "食材；原料",
      "咖喱角",
      "鸡饭"
    ],
    pronunciation: [
      "/dɪʃ/",
      "/lʌntʃ/",
      "/stɔːl/",
      "/bʌz/",
      "/hoʊp/",
      "/sneɪk/",
      "/ˈkrɪspi/",
      "/ˈspaɪsi/",
      "/dɪˈlɪʃəs/",
      "/ˈteɪstləs/",
      "/freʃ/",
      "/dɪsˈɡʌstɪŋ/",
      "/ɪnˈɡriːdiənts/",
      "/ˈkʌri pʌf/",
      "/ˈtʃɪkɪn raɪs/"
    ],
    sentences: [
      "My favourite <b><u>dish</u></b> is mee goreeng.",
      "I had nasi lemak for <b><u>lunch</u></b> yesterday afternoon.",
      "The <b><u>stall</u></b> that sells satay and ketupat is very crowded now.",
      "Sally was woken up by the <b><u>buzz</u></b> of a mosquito in her ear.",
      "We <b><u>hope</u></b> and pray that the operation will be a success.",
      "A <b><u>snake</u></b> slithered across our path.",
      "The fried chicken wings are <b><u>crispy</u></b> and tasty.",
      "The chilli is so <b><u>spicy</u></b> that I have to drink two big glasses water.",
      "The customers were very pleased with the <b><u>delicious</u></b> meal.",
      "The meat was dry and <b><u>tasteless</u></b>.",
      "Mother threw away the bread because it was not <b><u>fresh</u></b>.",
      "The food was so <b><u>disgusting</u></b> that none of us wanted to eat it.",
      "He created a fantastic meal from very few <b><u>ingredients</u></b>.",
      "I have eaten only one <b><u>curry puff</u></b> and I am already full.",
      "Mr Low tasted the <b><u>chicken rice</u></b> that he cooked and said that it was nice."
    ]
  },
  {
    title: "Unit 2 - Bad Dreams",
    subtitle: "Unit 2",
    testdate: "Test Date 09/02/2023",
    words: [
      "afraid",
      "sailed",
      "waited",
      "drain",
      "kitchen",
      "squirmed",
      "squeezed",
      "begged",
      "replied",
      "protected",
      "chose",
      "crowded",
      "comfortable",
      "fear",
      "full"
    ],
    meanings: [],
    meanings_cn: [
      "害怕的",
      "航行（过去式）",
      "等待（过去式）",
      "排水管；下水道",
      "厨房",
      "扭动（过去式）",
      "挤压（过去式）",
      "恳求（过去式）",
      "回答（过去式）",
      "保护（过去式）",
      "选择（过去式）",
      "拥挤的",
      "舒适的",
      "恐惧",
      "满的；饱的"
    ],
    pronunciation: [
      "/əˈfreɪd/",
      "/seɪld/",
      "/ˈweɪtɪd/",
      "/dreɪn/",
      "/ˈkɪtʃɪn/",
      "/skwɜːrmd/",
      "/skwiːzd/",
      "/beɡd/",
      "/rɪˈplaɪd/",
      "/prəˈtektɪd/",
      "/tʃoʊz/",
      "/ˈkraʊdɪd/",
      "/ˈkʌmftərbl/",
      "/fɪr/",
      "/fʊl/"
    ],
    sentences: [
      "The boys were <b><u>afraid</u></b> of the dark.",
      "The boat <b><u>sailed</u></b> down the coast.",
      "I <b><u>waited</u></b> patiently for my turn to ride the horse.",
      "There was an unpleasant smell coming from the <b><u>drain</u></b>.",
      "Mother is busy cooking in the <b><u>kitchen</u></b>.",
      "The earthworm <b><u>squirmed</u></b> when my sister poked it with a stick.",
      "We <b><u>squeezed</u></b> into the backseat of a small car yesterday.",
      "The old woman <b><u>begged</u></b> the rich man for some money.",
      '"I have not eaten my lunch," <b><u>replied</u></b> Sally.',
      "The dog <b><u>protected</u></b> its owner by barking fiercely at the robber.",
      "Mrs Lee <b><u>chose</u></b> the red box instead of the blue one.",
      "The shopping centre was <b><u>crowded</u></b> because there was a sale.",
      "He felt very <b><u>comfortable</u></b> sitting on that big sofa.",
      "Peter has a <b><u>fear</u></b> of sleeping alone.",
      "As the bed was <b><u>full</u></b>, there was little room for me to sleep."
    ]
  },
  {
    title: "Unit 3 - My Gumpy's Outing",
    subtitle: "Unit 3",
    testdate: "Test Date 23/02/2023",
    words: [
      "sheep",
      "stream",
      "creep",
      "pleaded",
      "bleated",
      "leaked",
      "teased",
      "trampled",
      "squabbled",
      "clasped",
      "flapped",
      "mucked",
      "owned",
      "field",
      "entrance"
    ],
    meanings: [],
    meanings_cn: [
      "绵羊",
      "小溪",
      "悄悄地走；爬行",
      "恳求（过去式）",
      "（羊等）咩咩叫（过去式）",
      "泄漏（过去式）",
      "取笑（过去式）",
      "践踏（过去式）",
      "争吵（过去式）",
      "紧握（过去式）",
      "拍打（过去式）",
      "混日子；瞎搞（过去式）",
      "拥有（过去式）",
      "田野",
      "入口"
    ],
    pronunciation: [
      "/ʃiːp/",
      "/striːm/",
      "/kriːp/",
      "/ˈpliːdɪd/",
      "/ˈbliːtɪd/",
      "/liːkt/",
      "/tiːzd/",
      "/ˈtræmpld/",
      "/ˈskwɒbld/",
      "/klæspt/",
      "/flæpt/",
      "/mʌkt/",
      "/oʊnd/",
      "/fiːld/",
      "/ˈentrəns/"
    ],
    sentences: [
      "The farmer kept the <b><u>sheep</u></b> for its wool.",
      "As the <b><u>stream</u></b> was quite shallow, we were able to walk across it.",
      "I tried to <b><u>creep</u></b> around the corner, hoping my brother would not see me.",
      "Karen <b><u>pleaded</u></b> with her mother for a shopping trip.",
      "The goat <b><u>bleated</u></b> weakly in hunger.",
      "The water pipe had <b><u>leaked</u></b> so we called a plumber to fix it.",
      "Harry <b><u>teased</u></b> his cousin when he made a mistake.",
      "The horses <b><u>trampled</u></b> on the flowers as they galloped across the field.",
      "The boys <b><u>squabbled</u></b> noisily over a ball during recess.",
      "We <b><u>clasped</u></b> each other's hands so that none of us would be lost in the crowd.",
      "A yellow bird <b><u>flapped</u></b> its wings furiously and flew off.",
      "The children <b><u>mucked</u></b> about all afternoon and wasted a lot of time.",
      "My Gumpy <b><u>owned</u></b> a boat and his house was by a river.",
      "I saw a fox run across the <b><u>field</u></b>.",
      "When we arrived at the zoo, we saw that the <b><u>entrance</u></b> was packed with tourists."
    ]
  },
  {
    title: "Unit 4 - A Day In the Kitchen with Grandma",
    subtitle: "Unit 4",
    testdate: "Test Date 09/03/2023",
    words: [
      "towel",
      "tooth",
      "noodles",
      "bamboo",
      "dough",
      "dumplings",
      "equipment",
      "refrigerator",
      "crushed",
      "stained",
      "shaped",
      "decorated",
      "stirred",
      "boiled",
      "fried"
    ],
    meanings: [],
    meanings_cn: [
      "毛巾",
      "牙齿",
      "面条",
      "竹子",
      "面团",
      "饺子；汤圆",
      "设备；器具",
      "冰箱",
      "压碎（过去式）",
      "弄脏（过去式）",
      "塑形（过去式）",
      "装饰（过去式）",
      "搅拌（过去式）",
      "煮沸（过去式）",
      "油炸（过去式）"
    ],
    pronunciation: [
      "/ˈtaʊəl/",
      "/tuːθ/",
      "/ˈnuːdlz/",
      "/bæmˈbuː/",
      "/doʊ/",
      "/ˈdʌmplɪŋz/",
      "/ɪˈkwɪpmənt/",
      "/rɪˈfrɪdʒəreɪtər/",
      "/krʌʃt/",
      "/steɪnd/",
      "/ʃeɪpt/",
      "/ˈdekəreɪtɪd/",
      "/stɜːrd/",
      "/bɔɪld/",
      "/fraɪd/"
    ],
    sentences: [
      "She used the kitchen <b><u>towel</u></b> to wipe the oily table.",
      "Grandma broke a <b><u>tooth</u></b> while she was eating some chilli crabs.",
      "I ordered chicken <b><u>noodles</u></b> for dinner.",
      "She wrapped the rice with <b><u>bamboo</u></b> leaves.",
      "Karen and her mother kneaded the <b><u>dough</u></b> to make bread.",
      "We eat rice <b><u>dumplings</u></b> during the Dragon Boat Festival.",
      "My parents went shopping for new kitchen <b><u>equipment</u></b> for our new house.",
      "Please keep the milk in the <b><u>refrigerator</u></b>.",
      "Grandma <b><u>crushed</u></b> the blue flowers to colour the rice.",
      "His shirt was <b><u>stained</u></b> with ink.",
      "The chef <b><u>shaped</u></b> with mixture into a ball.",
      "My siblings and I <b><u>decorated</u></b> the gingerbread cookied with icing.",
      "He <b><u>stirred</u></b> some milk into his coffee.",
      "Grandma <b><u>boiled</u></b> some eggs to add to the salad.",
      "My mother <b><u>fried</u></b> fish for yesterday's dinner."
    ]
  },
  {
    title: "Unit 5 - A butterfly is born",
    subtitle: "Unit 5",
    testdate: "Test Date 13/04/2023",
    words: [
      "nectar",
      "pupa",
      "shell",
      "leaves",
      "caterpillar",
      "butterflies",
      "branch",
      "watch",
      "crunch",
      "munch",
      "hatches",
      "crumpled",
      "amazed",
      "hungry",
      "happening"
    ],
    meanings: [],
    meanings_cn: [
      "花蜜",
      "蛹",
      "壳",
      "叶子（复数）",
      "毛毛虫",
      "蝴蝶（复数）",
      "树枝",
      "观看；手表",
      "嘎吱嘎吱地嚼",
      "大声咀嚼",
      "孵化（第三人称单数）",
      "弄皱（过去式）",
      "惊讶的",
      "饥饿的",
      "发生（进行时）"
    ],
    pronunciation: [
      "/ˈnektər/",
      "/ˈpjuːpə/",
      "/ʃel/",
      "/liːvz/",
      "/ˈkætərpɪlər/",
      "/ˈbʌtərflaɪz/",
      "/bræntʃ/",
      "/wɒtʃ/",
      "/krʌntʃ/",
      "/mʌntʃ/",
      "/ˈhætʃɪz/",
      "/ˈkrʌmpld/",
      "/əˈmeɪzd/",
      "/ˈhʌŋɡri/",
      "/ˈhæpənɪŋ/"
    ],
    sentences: [
      "Bees collect <b><u>nector</u></b> from flowers.",
      "A <b><u>pupa</u></b> is an insect in one stage of the life cycle of a butterfly.",
      "The <b><u>shell</u></b> of an egg is the hard covering which surrounds it.",
      "Many trees lose their <b><u>leaves</u></b> in the winter.",
      "The <b><u>caterpillar</u></b> turns into a butterfly.",
      "We tried to catch the <b><u>butterflies</u></b> with a net.",
      "The bat hangs from a <b><u>branch</u></b> to rest.",
      "We are going to <b><u>watch</u></b> a movie this Sunday.",
      "She is trying to <b><u>crunch</u></b> the ice cube in her mouth.",
      "We were shocked that she could <b><u>munch</u></b> her way through a big tub of popcorn.",
      "The egg <b><u>hatches</u></b> into a baby bird.",
      "Susan threw the <b><u>crumpled</u></b> piece of paper away.",
      "He was <b><u>amazed</u></b> when the magician pulled out a rabbit from his hat.",
      "The children are always <b><u>hungry</u></b> when they come home from school.",
      "Can you see what is <b><u>happening</u></b> in the neighbour's house?"
    ]
  },
  {
    title: "Unit 8 - Roti Prata",
    subtitle: "Unit 8",
    testdate: "Test Date 13/07/2023",
    words: [
      "tried",
      "carried",
      "patted",
      "flipped",
      "tossed",
      "arrived",
      "sprinkled",
      "stretched",
      "celebrate",
      "excited",
      "afternoon",
      "harmony",
      "friends",
      "students",
      "principal"
    ],
    meanings: [],
    meanings_cn: [
      "尝试（过去式）",
      "搬运（过去式）",
      "轻拍（过去式）",
      "翻转（过去式）",
      "抛掷（过去式）",
      "到达（过去式）",
      "撒（过去式）",
      "拉伸（过去式）",
      "庆祝",
      "兴奋的",
      "下午",
      "和谐",
      "朋友（复数）",
      "学生（复数）",
      "校长"
    ],
    pronunciation: [
      "/traɪd/",
      "/ˈkærid/",
      "/ˈpætɪd/",
      "/flɪpt/",
      "/tɒst/",
      "/əˈraɪvd/",
      "/ˈsprɪŋkld/",
      "/stretʃt/",
      "/ˈselɪbreɪt/",
      "/ɪkˈsaɪtɪd/",
      "/ˌæftərˈnuːn/",
      "/ˈhɑːrməni/",
      "/frendz/",
      "/ˈstuːdnts/",
      "/ˈprɪnsəpl/"
    ],
    sentences: [
      "I <b><u>tried</u></b> a few times to wrap the rice dumpling, but failed.",
      "He <b><u>carried</u></b> the books to the staffroom.",
      "My mother <b><u>patted</u></b> the vegetables dry with a paper towel.",
      "She dropped the pancake onto the floor when she <b><u>flipped</u></b> it.",
      "We <b><u>tossed</u></b> the coin to see which one of us would start the game.",
      "My dog wagged its tail when the guests <b><u>arrived</u></b> at the gate.",
      "Mary <b><u>sprinkled</u></b> some chocolate chips on the muffins.",
      "He <b><u>stretched</u></b> the roti prata dough by pulling the sides.",
      "This year, I will <b><u>celebrate</u></b> my birthday at home instead of dining out at a restaurant.",
      "James was so <b><u>excited</u></b> about the learning journey that he could not sleep all night.",
      "My brother enjoys taking a nap every <b><u>afternoon</u></b>.",
      "Although there are several races in the country, the people live together in <b><u>harmony</u></b>.",
      "Alice has made many <b><u>friends</u></b> in the new school within one month.",
      "The <b><u>students</u></b> have been reminded to wear their face masks properly.",
      "The <b><u>principal</u></b> praised Martin for returing the wallet."
    ]
  },
  {
    title: "Unit 9 - Magnetic Max",
    subtitle: "Unit 9",
    testdate: "Test Date 27/07/2023",
    words: [
      "salt",
      "dark",
      "shrugged",
      "answer",
      "odd",
      "amazing",
      "enormous",
      "carefully",
      "ribbon",
      "ladder",
      "magnet",
      "skateboard",
      "anything",
      "everyone",
      "neighbourhood"
    ],
    meanings: [],
    meanings_cn: [
      "盐",
      "黑暗的",
      "耸肩（过去式）",
      "回答",
      "奇怪的",
      "惊人的",
      "巨大的",
      "小心地",
      "丝带",
      "梯子",
      "磁铁",
      "滑板",
      "任何事物",
      "每个人",
      "邻里；社区"
    ],
    pronunciation: [
      "/sɔːlt/",
      "/dɑːrk/",
      "/ʃrʌɡd/",
      "/ˈænsər/",
      "/ɒd/",
      "/əˈmeɪzɪŋ/",
      "/ɪˈnɔːrməs/",
      "/ˈkerfəli/",
      "/ˈrɪbən/",
      "/ˈlædər/",
      "/ˈmæɡnɪt/",
      "/ˈskeɪtbɔːrd/",
      "/ˈeniθɪŋ/",
      "/ˈevriwʌn/",
      "/ˈneɪbərhʊd/"
    ],
    sentences: [
      "I add a pinch of <b><u>salt</u></b> to the soup so that it is more flavourful.",
      "The children refuse to go into the <b><u>dark</u></b> room unless you turn on the light.",
      "He <b><u>shrugged</u></b> his shoulders as if to say that he was not interested in the game.",
      "Nobody could <b><u>answer</u></b> that difficult question.",
      "James felt a little <b><u>odd</u></b> having to wear a pink wig for the play.",
      "We had an <b><u>amazing</u></b> holiday in Japan two years ago.",
      "That elephant looks <b><u>enormous</u></b> when it is compared with the tiny mouse.",
      '"The floor is wet. Please walk <b><u>carefully</u></b>." warned the teacher.',
      "Mother tied a pretty <b><u>ribbon</u></b> around the Chrismas present.",
      "The firefighters used a <b><u>ladder</u></b> to rescue the kitten in the tree.",
      "Max used the <b><u>magnet</u></b> to move the toy car made of steel.",
      "It is not easy to balance on a <b><u>skateboard</u></b>.",
      "My brother did not want to do <b><u>anything</u></b> as he was tired.",
      "Lisa told <b><u>everyone</u></b> to listen attentively to her story.",
      "Every evening, my sister and I take a walk around the <b><u>neighbourhood</u></b>."
    ]
  },
  {
    title: "Unit 10 - A Snake In the Garden",
    subtitle: "Unit 10",
    testdate: "Test Date 17/08/2023",
    words: [
      "phone",
      "chef",
      "ache",
      "marched",
      "returned",
      "dangerous",
      "tomatoes",
      "vegetable",
      "pale",
      "gigantic",
      "difficult",
      "glared",
      "sighed",
      "shocked",
      "apologised"
    ],
    meanings: [],
    meanings_cn: [
      "电话",
      "厨师",
      "疼痛",
      "行军（过去式）",
      "归还；返回（过去式）",
      "危险的",
      "西红柿（复数）",
      "蔬菜",
      "苍白的",
      "巨大的",
      "困难的",
      "怒视（过去式）",
      "叹气（过去式）",
      "震惊的",
      "道歉（过去式）"
    ],
    pronunciation: [
      "/foʊn/",
      "/ʃef/",
      "/eɪk/",
      "/mɑːrtʃt/",
      "/rɪˈtɜːrnd/",
      "/ˈdeɪndʒərəs/",
      "/təˈmeɪtoʊz/",
      "/ˈvedʒtəbl/",
      "/peɪl/",
      "/dʒaɪˈɡæntɪk/",
      "/ˈdɪfɪkəlt/",
      "/ɡlerd/",
      "/saɪd/",
      "/ʃɒkt/",
      "/əˈpɒlədʒaɪzd/"
    ],
    sentences: [
      "Father took out his <b><u>phone</u></b> to call the snake-catcher.",
      "The <b><u>chef</u></b> is busy preparing food in the kitchen for the wedding feast.",
      "He complained of an <b><u>ache</u></b> in his shoulder which kept him awake all night.",
      "The band <b><u>marched</u></b> through the streets.",
      "He <b><u>returned</u></b> the book to its place on the shelf after reading it.",
      '"It is <b><u>dangerous</u></b> to play in the kitchen," Mother warned me.',
      "There are many fresh <b><u>tomatoes</u></b> in the garden.",
      "My parents love to eat <b><u>vegetable</u></b> pies.",
      "She looked <b><u>pale</u></b> and tired after working through the night.",
      "Mei Ling found a <b><u>gigantic</u></b> snake in the garden.",
      "Little Henry found it very <b><u>difficult</u></b> to tie his shoelaces.",
      "Mr Lee <b><u>glared</u></b> at his son when he refused to do his homework.",
      "Muthu <b><u>sighed</u></b> with regret when his teacher told him to redo his work neatly.",
      "The children were <b><u>shocked</u></b> when their mother came home from the salon with pink hair.",
      "The boy <b><u>apologised</u></b> to Mrs Tan for breaking her window."
    ]
  },
  {
    title: "Unit 11 - The Feast",
    subtitle: "Unit 11",
    testdate: "Test Date 30/08/2023",
    words: [
      "feast",
      "bobbed",
      "pranced",
      "stamped",
      "thumped",
      "swoosh",
      "cross",
      "furious",
      "fabulous",
      "dragon",
      "dinosaur",
      "homemade",
      "midnight",
      "invitation",
      "nonsense"
    ],
    meanings: [],
    meanings_cn: [
      "盛宴",
      "上下摆动（过去式）",
      "雀跃；昂首阔步（过去式）",
      "跺脚（过去式）",
      "砰地放下；重击（过去式）",
      "呼啸声",
      "生气的",
      "愤怒的",
      "极好的",
      "龙",
      "恐龙",
      "自制的",
      "午夜",
      "邀请",
      "胡说；无意义的话"
    ],
    pronunciation: [
      "/fiːst/",
      "/bɒbd/",
      "/prænst/",
      "/stæmpt/",
      "/θʌmpt/",
      "/swʊʃ/",
      "/krɒs/",
      "/ˈfjʊəriəs/",
      "/ˈfæbjələs/",
      "/ˈdræɡən/",
      "/ˈdaɪnəsɔːr/",
      "/ˌhoʊmˈmeɪd/",
      "/ˈmɪdnaɪt/",
      "/ˌɪnvɪˈteɪʃn/",
      "/ˈnɒnsəns/"
    ],
    sentences: [
      "We had a <b><u>feast</u></b> of fresh seafood to celebrate Chinese New Year.",
      "After feeding the puppy, Mrs Tan <b><u>bobbed</u></b> down again behind the computer to continue with her work.",
      "The little boy <b><u>pranced</u></b> cross the room in his cowboy costume.",
      "She <b><u>stamped</u></b> her feet and stormed out of the room in anger.",
      "My grandfather <b><u>thumped</u></b> down the stairs and flopped into his armchair.",
      "I heard cars <b><u>swoosh</u></b> through the streets.",
      "Mother was <b><u>cross</u></b> with me because I did not finish my homework.",
      "He was <b><u>furious</u></b> that I was late for our appointment.",
      "My mother looked <b><u>fabulous</u></b> in her new dress.",
      "A <b><u>dragon</u></b> is a large, immaginary animal that can blow fire out of its mouth.",
      "The triceratops is a plant-eating <b><u>dinosaur</u></b> with three horns and a large frill on its head.",
      "Aunt Kelly sold her <b><u>homemade</u></b> bread at the market.",
      "They did not arrive at their hotel until after <b><u>midnight</u></b>.",
      "We received an <b><u>invitation</u></b> to Asher's birthday party.",
      "No one listened to what he said as it was utter <b><u>nonsense</u></b> as usual."
    ]
  },
  {
    title: "Unit 12 - Willy And Hugh",
    subtitle: "Unit 12",
    testdate: "Test Date 21/09/2023",
    words: [
      "sneered",
      "appeared",
      "lonely",
      "nasty",
      "useless",
      "surrounded",
      "interesting",
      "panicked",
      "terrifying",
      "intelligent",
      "patiently",
      "nervously",
      "except",
      "themselves",
      "library"
    ],
    meanings: [],
    meanings_cn: [
      "嘲笑（过去式）",
      "出现（过去式）",
      "孤独的",
      "令人讨厌的",
      "无用的",
      "包围（过去式）",
      "有趣的",
      "惊慌（过去式）",
      "令人恐惧的",
      "聪明的",
      "耐心地",
      "紧张地",
      "除了",
      "他们自己",
      "图书馆"
    ],
    pronunciation: [
      "/snɪrd/",
      "/əˈpɪrd/",
      "/ˈloʊnli/",
      "/ˈnæsti/",
      "/ˈjuːsləs/",
      "/səˈraʊndɪd/",
      "/ˈɪntrəstɪŋ/",
      "/ˈpænɪkt/",
      "/ˈterɪfaɪɪŋ/",
      "/ɪnˈtelɪdʒənt/",
      "/ˈpeɪʃntli/",
      "/ˈnɜːrvəsli/",
      "/ɪkˈsept/",
      "/ðəmˈselvz/",
      "/ˈlaɪbreri/"
    ],
    sentences: [
      "She <b><u>sneered</u></b> at my new watch because it was not expensive.",
      "He suddenly <b><u>appeared</u></b> in the doorway and gave us a shock.",
      "Jane feels very <b><u>lonely</u></b> because nobody talks to her.",
      "Nobody likes Jimmy because he is always <b><u>nasty</u></b> to people.",
      "The boys did not let Willy join in any games as they felt he was <b><u>useless</u></b>.",
      "The policemen caught up with the thief and <b><u>surrounded</u></b> him.",
      "She has a lot of <b><u>interesting</u></b> ideas for the Science project.",
      "When Danny was about to jump over the hurdle, he <b><u>panicked</u></b> and fell.",
      "Lisa heared a <b><u>terrifying</u></b> noise from the room next door.",
      "The <b><u>intelligent</u></b> and hardworking student scored full marks for all his test.",
      "He waited <b><u>patiently</u></b> for his turn to play on the slide.",
      "She entered the examination room <b><u>nervously</u></b>.",
      "Everyone seemed to have friends <b><u>except</u></b> Willy.",
      "They enjoyed <b><u>themselves</u></b> very much at the party.",
      "We go to <b><u>library</u></b> every Sunday to borrow books."
    ]
  },
  {
    title: "Unit 13 - Postcards To David",
    subtitle: "Unit 13",
    testdate: "Test Date 12/10/2023",
    words: [
      "January",
      "February",
      "July",
      "hazy",
      "windy",
      "merry",
      "crying",
      "syrup",
      "climb",
      "write",
      "thinking",
      "through",
      "ground",
      "postcard",
      "special"
    ],
    meanings: [],
    meanings_cn: [
      "一月",
      "二月",
      "七月",
      "有雾霾的",
      "有风的",
      "快乐的",
      "哭泣（进行时）",
      "糖浆",
      "攀爬",
      "写",
      "思考（进行时）",
      "穿过",
      "地面",
      "明信片",
      "特别的"
    ],
    pronunciation: [
      "/ˈdʒænjuəri/",
      "/ˈfebrʊəri/",
      "/dʒʊˈlaɪ/",
      "/ˈheɪzi/",
      "/ˈwɪndi/",
      "/ˈmeri/",
      "/ˈkraɪɪŋ/",
      "/ˈsɪrəp/",
      "/klaɪm/",
      "/raɪt/",
      "/ˈθɪŋkɪŋ/",
      "/θruː/",
      "/ɡraʊnd/",
      "/ˈpoʊstkɑːrd/",
      "/ˈspeʃl/"
    ],
    sentences: [
      "David is starting school in <b><u>January</u></b>.",
      "He was born in <b><u>February</u></b>.",
      "We moved house in <b><u>July</u></b>.",
      "The sky was <b><u>hazy</u></b> because of the forest fire.",
      "On <b><u>windy</u></b> days, the children fly their kites in the park.",
      "We could hear the <b><u>merry</u></b> sound of laughter coming from the class party.",
      "The baby is <b><u>crying</u></b> for milk as he is hungry.",
      "Mother poured some <b><u>syrup</u></b> into the drink to sweeten it.",
      "As Ron is strong, he is able to <b><u>climb</u></b> up the rock wall easily.",
      "Our teachers always remind us to <b><u>write</u></b> our words clearly.",
      "David is <b><u>thinking</u></b> of a solution to the problem.",
      "We had to watch out for snakes as we walked <b><u>through</u></b> the jungle.",
      "We had to sit on the <b><u>ground</u></b> as there were no chairs around.",
      "A <b><u>postcard</u></b> can be mailed without an envelope.",
      "Oliver and his brother made a <b><u>special</u></b> effort to bake a cake for their mother."
    ]
  },
  {
    title: "Unit 14 - The Bicycle Race",
    subtitle: "Unit 14",
    testdate: "Test Date 08/11/2023",
    words: [
      "blacksmith",
      "trishaw",
      "overjoyed",
      "grateful",
      "different",
      "because",
      "retired",
      "cheered",
      "bicycle",
      "wheelchair",
      "recycling",
      "pedalled",
      "project",
      "colourful",
      "disappointed"
    ],
    meanings: [],
    meanings_cn: [
      "铁匠",
      "三轮车",
      "非常高兴的",
      "感激的",
      "不同的",
      "因为",
      "退休（过去式）",
      "欢呼（过去式）",
      "自行车",
      "轮椅",
      "回收",
      "踩踏板（过去式）",
      "项目",
      "色彩鲜艳的",
      "失望的"
    ],
    pronunciation: [
      "/ˈblæksmɪθ/",
      "/ˈtraɪʃɔː/",
      "/ˌoʊvərˈdʒɔɪd/",
      "/ˈɡreɪtfl/",
      "/ˈdɪfrənt/",
      "/bɪˈkɒz/",
      "/rɪˈtaɪərd/",
      "/tʃɪrd/",
      "/ˈbaɪsɪkl/",
      "/ˈwiːltʃer/",
      "/riːˈsaɪklɪŋ/",
      "/ˈpedld/",
      "/ˈprɒdʒekt/",
      "/ˈkʌlərfl/",
      "/ˌdɪsəˈpɔɪntɪd/"
    ],
    sentences: [
      "A <b><u>blacksmith</u></b> is a person who makes and repairs iron objects and horseshoes.",
      "The <b><u>trishaw</u></b> was a popular type of transportation in Singapore many years ago.",
      "They were <b><u>overjoyed</u></b> to learn that their son had not been injured in the accident.",
      "The survivors were <b><u>grateful</u></b> to be alive after the earthquake.",
      "The Asian elephants are <b><u>different</u></b> from the African elephants.",
      "The road was flooded <b><u>because</u></b> it rained heavily.",
      "Aunt Sarah has <b><u>retired</u></b> from her job two years ago.",
      "The spectators <b><u>cheered</u></b> him on as he struggled to reach the finishing line after his fall.",
      "Uncle Lim fixed a set of training wheels on the <b><u>bicycle</u></b> for his grandson to cycle.",
      "Kate injured her leg and had to use the <b><u>wheelchair</u></b> when she was in school.",
      "David found some useful things from the <b><u>recycling</u></b> bin that could be reused.",
      "He <b><u>pedalled</u></b> hard to go up the steep slope.",
      "The teacher gave me some materials to help me complete the <b><u>project</u></b>.",
      "I designed a <b><u>colourful</u></b> card for my mother.",
      "Paul was <b><u>disappointed</u></b> as the trip to the zoo was cancelled due to the rain."
    ]
  }
];
